### ISSUE TITLE
Need an architecture diagram to indicate the relationship and dataflow of the DevOps tools

### ISSUE THREAD

**Issue by luotian-github** [inspursoft/DevOps#15]
Need an architecture diagram to indicate the relationship and dataflow of the DevOps tools

![图片](https://user-images.githubusercontent.com/28591924/93177111-de80e180-f764-11ea-8b9d-024344dfc198.png)

**Comment by yhua123** [comment]
do you mean the diagram like this?
![image](https://user-images.githubusercontent.com/19166125/93416209-e0b77d00-f8d7-11ea-98d4-097ac261d8f1.png)

**Comment by luotian-github** [comment]
Yes, like this.
The custmer values of this project cloud be the following:
Guide to setup a DevOps system by our provided tools and use DevOps system in development work.
Advertise our perspectives and thoughts on DevOps
Share our experiences during the CCSA DevOps assessment, get some benefits if want to attend the DevOps assessment

**Comment by yhua123** [comment]
https://github.com/inspursoft/DevOps/blob/master/docs/imgs/DevOps%E6%B5%81%E7%A8%8B/devops_process.png

**Comment by yhua123** [comment]
https://github.com/inspursoft/DevOps/tree/master/DevOps工具集

updated
