### ISSUE TITLE
CD-BCI-BP-BM-L4-01-服务化构建系统相关文档  is empty, need more contents

### ISSUE THREAD

**Issue by luotian-github** [inspursoft/DevOps#17]
CD-BCI-BP-BM-L4-01-服务化构建系统相关文档  is empty, need more contents

**Comment by yhua123** [comment]
on fixing

[https://github.com/yhua123/DevOps/blob/master/DevOps流程/03 构建实践/10、《CD-BCI-BP-BM-L4-01-服务化构建系统相关文档》.md](https://github.com/yhua123/DevOps/blob/master/DevOps%E6%B5%81%E7%A8%8B/03%20%E6%9E%84%E5%BB%BA%E5%AE%9E%E8%B7%B5/10%E3%80%81%E3%80%8ACD-BCI-BP-BM-L4-01-%E6%9C%8D%E5%8A%A1%E5%8C%96%E6%9E%84%E5%BB%BA%E7%B3%BB%E7%BB%9F%E7%9B%B8%E5%85%B3%E6%96%87%E6%A1%A3%E3%80%8B.md)
